<?php
$this->headTitle('Mon profil');
?>

<div class="row-fluid">
    <div class="span1">
        <?php echo $this->gravatar($this->user->gravatar, array('imgSize' => 146, 'secure' => true), array('class' => 'img-polaroid avatar')); ?>
    </div>
    <div class="span11">
        <div class="box-small-title"><?php echo $this->user->role->name; ?></div>
    </div>
</div>


<div class="row-fluid">
    <div class="box span12">
        
        <div class="box-header">
            <h2><i class="icon-edit"></i><span class="break"></span>Modifier mon profil</h2>
        </div>
        
        <div class="box-content">
            
            <!-- update form -->
            <form class="form-horizontal" method="post" action="">
                <fieldset>
                    
                    <?php echo $this->form->triggerUpdate; ?> 
                    
                    <div class="control-group">
                        <label class="control-label" for="">Prénom</label>
                        <div class="controls">
                          <input class="input-xlarge" id="firstname" name="firstname" type="text" value="<?php echo $this->form->getValue('firstname'); ?>">
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label class="control-label" for="">Nom</label>
                        <div class="controls">
                          <input class="input-xlarge" id="name" name="name" type="text" value="<?php echo $this->form->getValue('name'); ?>">
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label class="control-label" for="">Date de naissance</label>
                        <div class="controls">
                            <input class="input-xlarge" id="birthday" name="birthday" type="text" value="<?php echo $this->form->getValue('birthday'); ?>" >
                            <span class="help-inline red">Requis</span>
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label class="control-label" for="">Pseudo</label>
                        <div class="controls">
                          <input class="input-xlarge" id="username" name="username" type="text" value="<?php echo $this->form->getValue('username'); ?>" disabled>
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label class="control-label" for="prependedInput">E-mail</label>
                        <div class="controls">
                            <input id="mail" class="input-xlarge" name="mail" size="16" type="text" value="<?php echo $this->form->getValue('mail'); ?>">
                            <span class="help-inline red">Requis</span>
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label class="control-label" for="">E-mail Gravatar</label>
                        <div class="controls">
                          <input class="input-xlarge" id="mailGravatar" name="mailGravatar" type="text" value="<?php echo $this->form->getValue('mailGravatar'); ?>" >
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label class="control-label" for="">Site web</label>
                        <div class="controls">
                          <input class="input-xxlarge" id="website" name="website" type="text" value="<?php echo $this->form->getValue('website'); ?>" >
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label class="control-label" for="">A propos de moi</label>
                        <div class="controls">
                            <textarea name="about" id="about" class="input-xxlarge" rows="5" cols="80"><?php echo $this->form->getValue('about'); ?></textarea>
                        </div>
                    </div>
                    
                    <div class="form-actions">
                        <button type="submit" name="submit" id="submit" class="btn btn-primary btn-submit">Enregistrer</button>
                        <button class="btn" type="reset">Annuler</button>
                    </div>
                    
                </fieldset>
            </form>
            
        </div>
    </div><!--/span-->
</div>

<!-- UPDATE PREFERENCE -->
<div class="row-fluid">
    <div class="box span12">
        
        <div class="box-header">
            <h2><i class="icon-edit"></i><span class="break"></span>Modifier mes préférences</h2>
        </div>
        
        <div class="box-content">
            
            <!-- update form -->
            <form class="form-horizontal" method="post" action="">
                <fieldset>
                    
                    <?php echo $this->formPref->triggerUpdatePref; ?> 
                    
                    <div class="control-group">
                        <label class="control-label" for="">Nom à afficher publiquement</label>
                        <div class="controls">
                            <?php echo $this->formPref->getElement('preference_authorDisplayName')->renderViewHelper(); ?>
                        </div>
                    </div>
                    
                    <div class="form-actions">
                        <button type="submit" name="submit" id="submit" class="btn btn-primary btn-submit">Enregistrer</button>
                        <button class="btn" type="reset">Annuler</button>
                    </div>
                    
                </fieldset>
            </form>
            
        </div>
    </div><!--/span-->
</div>


<!-- UPDATE PASSWORD -->
<div class="row-fluid">
    <div class="box span12">
        
        <div class="box-header">
            <h2><i class="icon-edit"></i><span class="break"></span>Modifier mon mot de passe</h2>
        </div>
        
        <div class="box-content">
            
            <!-- update form -->
            <form class="form-horizontal" method="post" action="">
                <fieldset>
                    
                    <?php echo $this->formPassword->triggerUpdatePassword; ?>
                    
                    <div class="control-group">
                        <label class="control-label" for="">Ancien mot de passe</label>
                        <div class="controls">
                            <input class="input-xlarge" id="oldPassword" name="oldPassword" type="password" value="" >
                            <span class="help-inline red">Requis</span>
                        </div>
                    </div>
                    
                    <div class="control-group">
                        <label class="control-label" for="">Mot de passe</label>
                        <div class="controls">
                            <input class="input-xlarge" id="password" name="password" type="password" value="" data-toggle="tooltip" data-placement="top" data-original-title="Le mot de passe dois faire au moins 4 caractères de long. Pour le rendre plus sûr, combinez des majuscules, minuscules, et des chiffres.">
                            <span class="help-inline red">Requis</span>
                        </div>
                    </div> 
                    
                    <div class="control-group">
                        <label class="control-label" for="">Retapez le mot de passe</label>
                        <div class="controls">
                            <input class="input-xlarge" id="checkPassword" name="checkPassword" type="password" value="" data-toggle="tooltip" data-placement="top" data-original-title="">
                            <span class="help-inline red">Requis</span>
                        </div>
                    </div>  
                    
                    <div class="form-actions">
                        <button type="submit" name="submit" id="submit" class="btn btn-primary btn-submit">Enregistrer</button>
                        <button class="btn" type="reset">Annuler</button>
                    </div>
                </fieldset>
            </form>
            
        </div>
    </div><!--/span-->
</div>


<script>
    $(function() {
        $( "#birthday" ).datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "1950:"
        });
    });
</script>