<?php
$this->headTitle('Utilisateurs');
?>

<div class="row-fluid">		
    <div class="box span12">
        
        <div class="box-header" data-original-title="">
            <h2><i class="icon-user"></i><span class="break"></span>Catégories enregistrées</h2>
        </div>
        
        <div class="box-content">
            
            <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
                <thead>
                    <tr>
                        <th style="width: 50px;">Identifiant</th>
                        <th>Pseudo</th>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Rôle</th>
                        <th>Mail</th>
                        <th style="width: 95px;">Action</th>
                    </tr>
                </thead>   

                <tbody >

                    <?php foreach($this->users as $user): ?>
                    <tr>
                        <td><?php echo $user->id; ?></td>
                        <td class="center "><?php echo $user->username; ?></td>
                        <td class="center "><?php echo $user->name; ?></td>
                        <td class="center "><?php echo $user->firstname; ?></td>
                        <td class="center "><?php echo $user->role->name; ?></td>
                        <td class="center "><?php echo $user->mail; ?></td>
                        <td class="center ">
                            
                            <!-- update -->
                            <?php if( $user->id == $this->userIdentity()->id ): ?>
                            <!-- mon profil -->
                            <a title="Modifier" class="btn btn-info" href="<?php echo $this->url(array('controller'=> 'user', 'action' => 'update', 'module' => 'admin'),'default',false); ?>">
                            <?php else: ?>
                            <!-- autre profil -->
                            <a title="Modifier" class="btn btn-info" href="<?php echo $this->url(array('controller'=> 'user', 'action' => 'updateuser', 'module' => 'admin', 'id' => $user->id),'default',true); ?>">
                            <?php endif; ?>  
                                <i class="icon-edit icon-white"></i>
                            </a>
                            
                            <!-- delete -->
                            <?php if( $user->id != $this->userIdentity()->id ): ?>
                            <a class="btn btn-danger " href="<?php echo $this->url(array('controller'=> 'user', 'action' => 'removeuser', 'module' => 'admin', 'id' => $user->id),'default',true); ?>" >
                                <i class="icon-trash icon-white"></i> 
                            </a>
                            <?php endif; ?>
                            
                        </td>
                    </tr>
                    <?php endforeach; ?>

                </tbody>
            </table>
        </div>            
    </div>
</div><!--/span-->
