<div class="navbar">
    <div class="navbar-inner">
        <div class="container-fluid">
            
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            
            <a class="brand" href="<?php echo $this->url(array(),'admin'); ?>"> <img alt="Administration" src="<?php echo RESOURCES_BASEURL . '/images/logo_32.png'; ?>" /> <span class="hidden-phone">Administration</span></a>

                    <!-- start: Header Menu -->
                    <div class="nav-no-collapse header-nav">
                        
                        <ul class="nav pull-right">

                            <!-- Retour site -->
                            <li>
                                <a class="btn" href="<?php echo $this->url(array('module' => 'default'), null, true); ?>" title="Retour au site BDE Miage Nancy">
                                    <i class="icon-home icon-white"></i>
                                    <span class="white">Retour site</span>
                                </a>
                            </li>
                            <!-- end: Retour site -->           

                            <!-- start: User Dropdown -->
                            <li class="dropdown">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="icon-user icon-white"></i>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url(array(), 'profil'); ?>"><i class="icon-user"></i> Profil</a></li>
                                    <li><a href="<?php echo $this->url(array(), 'logout'); ?>"><i class="icon-off"></i> Déconnexion</a></li>
                                </ul>
                            </li>
                            <!-- end: User Dropdown -->

                        </ul>
                    </div>
                    <!-- end: Header Menu -->

            </div>
    </div>
</div>
<!-- start: Header -->
