<?php echo $this->doctype() ?>
    
<?php

    /**
     * Theme Admin
     * perfectum_dashboard_1_0_5 (wrapbootstrap)
     * Information importante et ou suivant une maj:
     *  - datatable doit être remis en français dans custom.js
     *  - tooltip placement need fix in custom.js or use bootstrap tooltip
     *  - remove file-manager from custom.js and use it inside main program
     *      - configure settings (img folder)
     *      - possible fix for elfinder with delete https://github.com/Studio-42/elFinder/issues/415
     *  
     */
    $this->headLink()->appendStylesheet(RESOURCES_BASEURL . '/plugins/dashboard/css/bootstrap.min.css');
    $this->headLink()->appendStylesheet(RESOURCES_BASEURL . '/plugins/dashboard/css/bootstrap-responsive.css');
    $this->headLink()->appendStylesheet(RESOURCES_BASEURL . '/plugins/dashboard/css/style.css');
    $this->headLink()->appendStylesheet(RESOURCES_BASEURL . '/plugins/dashboard/css/style-responsive.css');
    $this->headLink()->appendStylesheet(RESOURCES_BASEURL . '/plugins/dashboard/css/jquery-ui-1.8.21.custom.css');
    $pathToJs = RESOURCES_BASEURL . '/plugins/dashboard/js/';
    $this->headScript()->offsetSetFile(0, ($pathToJs . "jquery-1.9.1.min.js"));
    $this->headScript()->offsetSetFile(1, ($pathToJs . "jquery-migrate-1.0.0.min.js"));
    $this->headScript()->offsetSetFile(2, ($pathToJs . "jquery-ui-1.10.0.custom.min.js"));
    $this->headScript()->offsetSetFile(3, ($pathToJs . "bootstrap.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.cookie.js"));
    $this->headScript()->appendFile(($pathToJs . "fullcalendar.min.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.dataTables.min.js"));
    $this->headScript()->appendFile(($pathToJs . "excanvas.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.flot.min.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.flot.pie.min.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.flot.stack.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.flot.resize.min.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.chosen.min.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.uniform.min.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.cleditor.min.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.noty.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.elfinder.min.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.raty.min.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.iphone.toggle.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.uploadify-3.1.min.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.gritter.min.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.imagesloaded.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.masonry.min.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.knob.js"));
    $this->headScript()->appendFile(($pathToJs . "jquery.sparkline.min.js"));
    $this->headScript()->appendFile(($pathToJs . "custom.js"));

    // TinyMce (plugin js pour la rédaction d'articles)
    $this->headScript()->offsetSetFile(500, RESOURCES_BASEURL . '/plugins/tinymce/jscripts/tiny_mce/tiny_mce.js');

    /**
     * Input limiter : http://rustyjeans.com/jquery-plugins/input-limiter
     * css must be prepended because of overwrite
     */
    $this->headScript()->appendFile(RESOURCES_BASEURL . '/plugins/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js');
    $this->headLink()->prependStylesheet(RESOURCES_BASEURL . '/plugins/jquery-inputlimiter/jquery.inputlimiter.1.0.css');


    // My script
    $this->headScript()->appendFile(RESOURCES_BASEURL . "/js/script.js");

?>
    
<?php if($this->isAuthContext()): ?>
    <?php echo $this->render('auth_container.phtml'); ?>
<?php else: ?>
    <?php echo $this->render('default_container.phtml'); ?>
<?php endif; 
