<?php
$this->headTitle('Gestion des fichiers');
?>
    
<div class="row-fluid ">
    <div class="span12">
        <div class="alert alert-error strong">
            Le dossier 'carousel' ne doit jamais être supprimé !
        </div>
        <div class="alert alert-info">
            <dl class="dl-horizontal">
                <dt>Changer les images<br> du carousel</dt>
                <dd>Se rendre dans le dossier 'carousel'. Les images doivent avoir une taille de 450*253 minimum et un ratio de 19:9. Pour éviter d'avoir une page trop longue à charger il est recommandé de respecter cette taille.</dd>
              </dl>
        </div>
    </div>
</div>

<div class="row-fluid ">
    <div class="box span12">
        <div class="box-header">
            <h2><i class="fa-icon-folder-open"></i><span class="break"></span>Gestionnaire de fichiers</h2>
        </div>
        <div class="box-content">
            <div class="file-manager"></div> <!-- Launch elfinder plugin from script.js -->
        </div>
    </div><!--/span-->
</div>
    

<script>
var fileManagerUrlConnector = '<?php echo RESOURCES_BASEURL; ?>/plugins/dashboard/misc/elfinder-connector/connector.php'; // local
$(document).ready(function(){
    /**
     * Gestion du filemanager
     * @type @call;$@call;elfinder@call;elfinder
     */
    var elf = $('.file-manager').elfinder({
           url : fileManagerUrlConnector
    }).elfinder('instance');   
});
</script>