<?php echo $this->doctype() ?>
    
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://ogp.me/ns/fb#" lang="fr">
    
<head>

    <?php
        $this->headTitle()->setPostfix(' - BDE Miage Nancy');
        
        // Jquery (jquery dois être chargé en premier)
        $this->headScript()->offsetSetFile(0, "https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js")
                           ->offsetSetFile(1, "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.min.js");
        $this->headLink()->prependStylesheet("http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/themes/smoothness/jquery-ui.css");

        // Bootstrap
        $this->headLink()->prependStylesheet(RESOURCES_BASEURL . '/plugins/bootstrap/css/bootstrap.css');
        $this->headScript()->appendFile(RESOURCES_BASEURL . "/plugins/bootstrap/js/bootstrap.min.js");
        
        // Coloration de code (<pre> <code>)
        $this->headLink()->appendStylesheet(RESOURCES_BASEURL . '/plugins/prettify/prettify.css');
        $this->headScript()->appendFile(RESOURCES_BASEURL . "/plugins/prettify/prettify.js");
        
        // Chosen (plugin js qui restyle les select)
        $this->headLink()->appendStylesheet(RESOURCES_BASEURL . '/plugins/harvesthq-chosen-v0.9.8-44-gdc024d7/chosen/chosen.css');
        $this->headScript()->appendFile(RESOURCES_BASEURL . '/plugins/harvesthq-chosen-v0.9.8-44-gdc024d7/chosen/chosen.jquery.min.js');
        
        // Font awesome (font icone fonctionne avec bootstrap)
        $this->headLink()->appendStylesheet(RESOURCES_BASEURL . "/plugins/font-awesome/css/font-awesome.css");
        $this->headLink()->appendStylesheet(RESOURCES_BASEURL . "/plugins/font-awesome-4.0.3/css/font-awesome.min.css");
         
        // http://tympanus.net/Development/ParallaxContentSlider/
        $this->headScript()->appendFile(RESOURCES_BASEURL . '/plugins/cslider/js/jquery.cslider.js');
        $this->headScript()->appendFile(RESOURCES_BASEURL . '/plugins/cslider/js/modernizr.custom.28468.js');
        $this->headLink()->appendStylesheet(RESOURCES_BASEURL . "/plugins/cslider/css/mystyle.css");

        // Noty (dynamic notification)
        $this->headScript()->appendFile(RESOURCES_BASEURL . '/plugins/noty-v2/js/noty/jquery.noty.js');
        $this->headScript()->appendFile(RESOURCES_BASEURL . '/plugins/noty-v2/js/noty/layouts/top.js');
        $this->headScript()->appendFile(RESOURCES_BASEURL . '/plugins/noty-v2/js/noty/themes/default.js');
        
        // My script
        $this->headScript()->appendFile(RESOURCES_BASEURL . "/js/script.js")
                           ->appendFile(RESOURCES_BASEURL . "/js/default/script.js");
        
        // My css
        $this->headLink()->appendStylesheet(RESOURCES_BASEURL . '/css/plugins.css')
                         ->appendStylesheet(RESOURCES_BASEURL . '/css/default/default.css');
        
        echo $this->headMeta();
        echo $this->headTitle();
        echo $this->headLink();
        echo $this->headScript();
    ?>
    
</head>

<body class="dark">
    
    <!--
    Facebook JDK loading
    -->
    <div id="fb-root"></div>
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '{your-app-id}',
          status     : true,
          xfbml      : true
        });
      };
      
      (function(d, s, id){
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    </script>
    
    <nav role="navigation" class="navbar navbar-fixed-top navbar-inverse navbar-toggle-hover" id="navbar">
        <div class="navbar-inner">
            <div class="container">

                    <button type="button" class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                
                    <a class="brand" href="<?php echo $this->url(array(), 'home'); ?>"><img src="<?php echo RESOURCES_BASEURL . '/images/logo_big.png'; ?>"/></a>

                    <div class="nav-collapse collapse" style="height: 0px;">

                        <!-- Navigation -->
                        <ul class="nav ">

                            <!-- Accueil -->
                            <li class="<?php echo $this->placeholder('nav_default_index_index'); ?>">
                                <a href="<?php echo $this->url(array(), 'home'); ?>"><i class="icon-home icon-white"></i></a>
                            </li>

                            <!-- Actualité -->
                            <li class="<?php echo $this->placeholder('nav_default_index_articles'); ?>">
                                <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'articles'), null, true); ?>"><i class="icon-refresh icon-white"></i> Actualités</a>
                            </li>

                            
                            <!-- Categories -->
                            <?php
                            /**
                             * Utilisation d'un placeholder pour gerer dynamiquement les categories
                             */
                            echo $this->placeholder('categoryDropdown');
                            ?>

                            <li class="divider-vertical"></li>

                            <!-- Pages statiques (extra) -->
                            <li class="<?php echo $this->placeholder('nav_default_extra_about'); ?>">
                                <a href="<?php echo $this->url(array(),'about'); ?>" title=""><i class="icon-question-sign icon-white"></i>  A propos de nous</a>
                            </li>
                            <li class="<?php echo $this->placeholder('nav_default_extra_contact'); ?>">
                                <a href="<?php echo $this->url(array(),'contact'); ?>"  title="Nous contacter"><i class="icon-envelope-alt icon-white"></i> Contact</a>
                            </li>

                        </ul>
                    </div>

                <?php if(is_null($user = $this->userIdentity())): ?>
                <div class="pull-right" style="padding: 4px 0px 4px;">
                    <a style=""class="btn btn-mini btn-login btn-info" title="Connexion" href="<?php echo $this->url(array(),'login'); ?>">Connexion</a>
                    <a rel="" title="Inscription" class="btn btn-mini btn-success" href="<?php echo $this->url(array(),'subscribe'); ?>">Inscription</a>
                </div>
                <?php else: ?>
                <ul class="nav pull-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle navbar-identity" dropdown-toggle-throw="false" >
                            Bienvenue, <?php echo $this->userIdentity()->username; ?>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('module' => 'admin'), null, true); ?>"><i class="icon-user"></i>&nbsp;&nbsp;Accès membre</a></li>
                            <li><a href="<?php echo $this->url(array(),'logout'); ?>"><i class="icon-signout" ></i>&nbsp;&nbsp;Déconnexion</a></li>
                        </ul>
                    </li>
                </ul>
                <?php endif; ?>
            </div>
        </div>
    </nav>
    
    <header id="header-main" role="banner">
        <div class=" header-logo-container">
            <a href="<?php echo $this->url(array(), 'home'); ?>" title="Accueil du site"></a>
        </div>
    </header>
    <?php echo $this->placeHolder('test'); ?>
    
    <!--
    Alert from administrators
    -->
    <?php if($this->messages('alert')): ?>
        <div class="container">
            <div class="alert alert-info"><span class="icon small gray" data-icon="i"></span>&nbsp;&nbsp;<?php echo $this->escape($this->messages('alert')[0]); ?></div>
        </div>
    <?php endif; ?>
    
    
    <?php echo $this->layout()->content ?>

    <?php echo $this->render('default_footer.phtml'); ?>
        
    
    <script>

          $(document).ready(function() {

                    
            /*var n = noty({
              text: '<?php //echo $this->flashmessenger(); ?>',
              type: 'alert',
              dismissQueue: false,
              layout: 'bottom',
              timeout: 5000
            });*/
            //generateAll();
            
//            $.noty.consumeAlert({layout: 'bottom', type: 'success', dismissQueue: false, timeout: 5000});

//            alert("This is the same but noty consumed with options");

//            $.noty.consumeAlert({layout: 'bottom', type: 'alert', dismissQueue: false, timeout: 5000});

//            alert("Consumed again but different options");

//            $.noty.stopConsumeAlert();

          });
    </script>
    
</body>
    
</html>
