<?php
$this->headTitle('Articles');
?>


<div class="row-fluid ">
    <div class="span12">
        <div class="alert alert-info">
            <dl class="dl-horizontal">
                <dt><span class="label label-success">Publié</span> <span class="label label-warning">Brouillon</span> <br><span class="label label-important">Mis en avant</span></dt>
                <dd>Désigne l'état de l'article. <span class="label label-important">Mis en avant</span> signifie que l'article est présent sur la page d'accueil</dd>
            </dl>
        </div>
    </div>
</div>


<div class="row-fluid">		
    <div class="box span12">
        
        <div class="box-header" data-original-title="">
                <h2><i class="icon-user"></i><span class="break"></span>Articles enregistrés</h2>
        </div>
        
        <div class="box-content">
            
            <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" id="DataTables_Table_1" aria-describedby="DataTables_Table_1_info">
                <thead>
                    <tr>
                        <th style="width: 50px;">Identifiant</th>
                        <th>Titre</th>
                        <th>Auteur</th>
                        <th>Mots-clefs</th>
                        <th class="sorting_desc date-eu">Date (publication)</th>
                        <th class="date-eu">Date (dernière modification)</th>
                        <th>Etat</th>
                        <th style="width: 130px;">Action</th>
                    </tr>
                </thead>

                <tbody>

                    <?php foreach($this->articles as $article): ?>
                    <tr>
                        <td><?php echo $article->id; ?></td>
                        <td class="center "><?php echo $article->title; ?></td>
                        <td class="center "><?php echo $article->author->username; ?></td>
                        <td class="center ">
                            <?php foreach($article->tags as $tag) echo '<span class="label label-success">' . $tag->label . '</span> '; ?>
                        </td>
                        <td class="center "><?php echo $this->date($article->date); ?></td>
                        <td class="center "><?php echo $this->date($article->lastEditionDate); ?></td>
                        <td class="center ">
                            <?php 
                            if($article->isPublished) echo '<span class="label label-success">Publié</span> '; 
                            else if($article->inTrash) echo '<span class="label ">Corbeille</span> ';
                            else echo '<span class="label label-warning">Brouillon</span> ';
                            if($article->putForward) echo '<span class="label label-important">Mis en avant</span> '
                            ?>
                        </td>
                        <td class="center ">
                            
                            <!-- trash -->
                            <?php if($article->inTrash): ?>
                                <a class="btn btn-danger" rel="tooltip" title="Restaurer" href="<?php echo $this->url(array('controller'=> 'article', 'action' => 'restore', 'module' => 'admin', 'id' => $article->id),'default',true); ?>">
                                    <i class="icon-refresh icon-white"></i>
                                </a>
                            <?php else: ?>
                            
                                <!-- display -->
                                <?php if($article->isPublished): ?>
                                    <a class="btn btn-success" rel="tooltip" title="Voir l'article" target="_blank" href="<?php echo $this->url(array('controller'=> 'index', 'action' => 'article', 'module' => 'default', 'id' => $article->id),'default',true); ?>">
                                        <i class="icon-zoom-in icon-white"></i>
                                    </a>
                                <?php else: ?>
                                    <a class="btn btn-warning" rel="tooltip" title="Prévisualiser" target="_blank" href="<?php echo $this->url(array('controller'=> 'index', 'action' => 'article', 'module' => 'default', 'id' => $article->id, 'preview' => 'true'),'default',true); ?>">
                                        <i class="icon-zoom-in icon-white"></i>
                                    </a>
                                <?php endif; ?>

                                <!-- update -->
                                <?php
                                // ayant droit OU auteur pouvant modifier un article
                                if( ($article->author->id === $this->userIdentity()->id && $this->isAllowed('admin_article', 'update') ) // auteur pouvant modifier un article
                                        || $this->isAllowed('admin_article', 'updateOther')):                                           // ayant droit
                                ?>
                                    <a class="btn btn-info" href="<?php echo $this->url(array('controller'=> 'article', 'action' => 'update', 'module' => 'admin', 'id' => $article->id),'default',true); ?>">
                                        <i class="icon-edit icon-white"></i>
                                    </a>
                                <?php endif; ?>


                                <!-- remove -->
                                <?php 
                                // La suppression peut se faire par l'auteur ou un utilisateur ayant les droits
                                if( ($article->author->id == $this->userIdentity()->id && $this->isAllowed('admin_article', 'remove') ) // auteur pouvant supprimer un article
                                        || $this->isAllowed('admin_article', 'removeOther')):                                           // ayant droit
                                ?>
                                    <a class="btn btn-danger confirm-action" rel="tooltip" title="Supprimer" href="<?php echo $this->url(array('controller'=> 'article', 'action' => 'remove', 'module' => 'admin', 'id' => $article->id),'default',true); ?>" data-message="L'article sera placé dans la corbeille et ne sera plus visible. Vous pourrez toujours le restaurer par la suite.">
                                        <i class="icon-trash icon-white"></i> 
                                    </a>
                                <?php endif; ?>
                                
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>

                </tbody>
            </table>
        </div>            
    </div>
</div><!--/span-->

