<?php
    $this->headTitle($this->article->title);
?>

<div class="container">
    <?php echo $this->generateBreadCrumb(); ?>
</div>

<!-- Container de page -->
<div class="container container-main" id="page-article">
    
    <!-- Ligne de contenu -->
    <div class="row row-content sidebar-container">
        <div class="span9">
            
            
            <!-- SECTION PRINCIPAL -->
            <section role="main">
                
                <!-- Article principal -->
                <article class="post">
                    <header>
                        
                        <time>
                            <span><?php echo $this->monthString($this->article->month, true); ?></span>
                            <span class="day"><?php echo $this->article->day; ?></span>
                        </time>
                        
                        <h1><?php echo $this->article->title; ?></h1>
                        
                        <!-- sub content -->
                        <div class="row-fluid content">
                            <div class="span12 author">
                                <i class="icon-folder-open"></i>  
                                <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'articles', 'cat' => $this->article->category->label), null, true); ?>" rel="tooltip-right" title="Rechercher les articles de la catégorie <?php echo $this->article->category->title; ?>"
                                   <span class="label label-warning"><?php echo $this->article->category->title; ?></span>
                                </a>
                            </div>
                        </div>
                        
                    </header>

                    <div class="post-wrapper">
                        
                        <section>
                            <?php echo $this->showArticleContent($this->article->content, $this->article->id, $cutContent = false); ?>
                        </section>

                        <hr>
                        
                        <footer >
                            <div class="row-fluid" >
                                <div class="span7">
                                    Rédigé par <?php echo $this->article->author->authorDisplayName; ?> le <?php echo $this->date($this->article->date, "dd-MM-yyyy"); ?>
                                </div>
                                <div class="span5 tags">
                                Mots clefs de l'article : 
                                    <?php foreach ($this->article->tags as $tag): ?>
                                    <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'articles', 'tag' => $tag->label), null, true); ?>" rel="tooltip" title="Recherche d'articles pour le tag : <?php echo $tag->label; ?>"><span class="label label-info"><?php echo $tag->label; ?></span></a>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                            <div class="row-fluid" >
                                <div class="fb-like" data-href="<?php echo $this->url(); ?>" data-layout="standard" data-action="recommend" data-show-faces="true" data-share="true"></div>
                            </div>
                        </footer>
                        
                    </div>
                </article>


                <!-- Commentaires -->
                <aside class="comments">
                    
                    <div id="disqus_thread"></div>
                    <script type="text/javascript">
                        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                        var disqus_shortname = 'bdemiagenancy'; // required: replace example with your forum shortname

                        /* * * DON'T EDIT BELOW THIS LINE * * */
                        (function() {
                            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                        })();
                    </script>
                    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

                </aside>
            </section>
        </div>
        
        
        <div class="span3">
            <?php echo $this->render('index/_sidebar.phtml'); ?>
        </div>
        
        
    </div>
</div>