
<h1><span class="icon x-large darkgray" data-icon="."></span> Articles</h1>


<div class="row-fluid">
    
    <div class="span12">
              
            
        <table class="table-users table table-striped table-bordered sortable">
        <thead>
            <tr>
            <th rel="0" value="id">#</th>
            <th rel="1" value="label">Label</th>
            <th rel="2" value="username">Titre</th>
            <th rel="3" value="date">Date de création</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->pages as $page): ?>

            <tr>
                <td><?php echo $page['id']; ?></td>
                <td><?php echo $page['label']; ?></td>
                <td>
                    <ul class="nav nav-pills">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><?php echo $page['title']; ?> <b class="caret"></b></a>
                            <ul id="menu2" class="dropdown-menu">
                                <li>
                                    <a href="<?php echo $this->url(array('controller'=> 'page', 'action' => 'update', 'module' => 'admin', 'label' => $page['label']),'default',true); ?>">Modifier</a>
                                </li>      
                            </ul>
                        </li>
                    </ul>
                </td>
                <td><?php echo $page['date']; ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        </table>
        
    </div>

</div>


<script type="text/javascript">
$(document).ready(function(){
    
    $('.dropdown-toggle').dropdown()
    
});
</script>