<?php
    $this->headTitle('A propos du bureau');
?>



<section>

    <blockquote>
        <p>Association « Loi 1901 » du Bureau des Etudiants de La Miage de Nancy.</p>
    </blockquote>

    <p>
        L’association dite « Bureau des Elèves de la Miage Nancy » fondée en 1974 a pour but :
        <ul >
            <li>D’établir entre tous ses membres des relations amicales et des liens de solidarité et d’entraide</li>
            <li>D’utiliser ces relations dans un but d’intérêt général et au profit des associations</li>
            <li>De contribuer à la prospérité et au rayonnement de la MIAGE , notamment en mettant en œuvre tous les moyens propres à assurer l’efficacité de l’enseignement pratiqué à la MIAGE</li>
        </ul>
    </p>

    <address>
    <strong>Bureau Des Étudiants MIAGE NANCY</strong><br>
    UFR Mathématiques et Informatique<br>
    13, rue Michel Ney<br>
    54000 NANCY<br>
    </address>

    <p>Les statuts de l'association sont disponibles <a href="<?php echo $this->url(array(),'statuts'); ?>">ici</a>.</p>

    <div class="followus">
        <h3>Nous suivre</h3>
        <hr>

        <p>Le site du BDE publie toutes les informations importantes concernant le bureau mais vous avez d'autres moyens de suivre nos actualités :</p>

        <div class="media">
            <a class="pull-left" href="https://www.facebook.com/pages/BDE-Miage-Nancy/136654919816299?sk=info">
                <img class="media-object" src="<?php echo RESOURCES_BASEURL . '/images/logo_48.png'; ?>">
            </a>
                <div class="media-body">
                  <h4 class="media-heading">Page Facebook</h4>

                <div class="media">
                    Vous pouvez nous retrouver sur Facebook et vous abonner à notre <a href="https://www.facebook.com/pages/BDE-Miage-Nancy/136654919816299?sk=info">page</a>.
                </div>
            </div>
        </div>

        <div class="media">
            <a class="pull-left" href="<?php echo $this->url(array(),'feed'); ?>">
                <img class="media-object" src="<?php echo RESOURCES_BASEURL . '/images/icon_rss_48.png'; ?>">
            </a>
                <div class="media-body">
                  <h4 class="media-heading">Flux RSS</h4>

                <div class="media">
                    Pour avoir les informations toutes fraîches du BDE Miage immédiatement un système RSS est aussi disponible <a href="<?php echo $this->url(array(),'feed'); ?>">ici</a>.
                </div>
            </div>
        </div>

    </div>

    <h3>Membres du bureau 2013 - 2014</h3>
    <hr>

    <div class="profil">
        <div class="avatar">
            <img class="thumbnail" src="<?php echo RESOURCES_BASEURL . '/images/avatar_president.jpg'; ?>"/>
        </div>
        <address>
            <strong>Président</strong><br>
            Baptiste Colona<br>
            <a href="mailto:#">president@bdemiagenancy.fr</a>
        </address>
    </div>

    <div class="profil">
        <div class="avatar">
            <img class="thumbnail" src="<?php echo RESOURCES_BASEURL . '/images/avatar_vp.jpg'; ?>"/>
        </div>
        <address>
            <strong>Vice-Président</strong><br>Alexandre Mathieu<br>
            <a href="mailto:#">vicepresident@bdemiagenancy.fr</a>
        </address>
    </div>

    <div class="profil">
        <div class="avatar">
            <img class="thumbnail" src="<?php echo RESOURCES_BASEURL . '/images/avatar_secretaire.jpg'; ?>"/>
        </div>
        <address>
            <strong>Secrétaire</strong><br>
            Emilien Casano<br>
            <a href="mailto:#">secretaire@bdemiagenancy.fr</a>
        </address>
    </div>

    <div class="profil">
        <div class="avatar">
            <img class="thumbnail" src="<?php echo RESOURCES_BASEURL . '/images/avatar_tresorier.jpg'; ?>"/>
        </div>
        <address>
            <strong>Trésorier</strong><br>Pierrick Chevrier<br>
            <a href="mailto:#">tresorier@bdemiagenancy.fr</a>
        </address>
    </div>

    <div class="profil"> 
        <div class="avatar">
            <img class="thumbnail" src="<?php echo RESOURCES_BASEURL . '/images/avatar_com.jpg'; ?>"/>
        </div>
        <address>
            <strong>Chargé de Communication</strong><br>Brian Dechoux<br>
            <a href="mailto:#">communication@bdemiagenancy.fr</a>
        </address>
    </div>

    <div class="profil">
        <div class="avatar">
            <img class="thumbnail" src="<?php echo RESOURCES_BASEURL . '/images/avatar_event.jpg'; ?>"/>
        </div>
        <address>
            <strong>Chargé Evénementiel</strong><br>
            Damien Carton<br>
            <a href="mailto:#">evenementiel@bdemiagenancy.fr</a>
        </address>
    </div>

    <div class="profil">
        <div class="avatar">
            <img class="thumbnail" src="<?php echo RESOURCES_BASEURL . '/images/avatar_vp_event.jpg'; ?>"/>
        </div>
        <address>
            <strong>Vice-Président Evénementiel</strong><br>
            Kevin Lambert<br>
            <a href="mailto:#">evenementiel@bdemiagenancy.fr</a>
        </address>
    </div>
    
    <div class="profil">
        <div class="avatar">
            <img class="thumbnail" src="<?php echo RESOURCES_BASEURL . '/images/avatar_webmaster.png'; ?>"/>
        </div>
        <address>
            <strong>Webmaster</strong><br>
            Maxime Bret<br>
            <a href="mailto:#">webmaster@bdemiagenancy.fr</a>
        </address>
    </div>
    
    <div class="profil">
        <div class="avatar">
            <img class="thumbnail" src="<?php echo RESOURCES_BASEURL . '/images/avatar_sportif1.jpg'; ?>"/>
        </div>
        <address>
            <strong>Résponsable Evénementiel sportif</strong><br>Joris Favier<br>
            <a href="mailto:#">evenementiel.sportif@bdemiagenancy.fr</a>
        </address>
    </div>
    
    <br>
    
    <div class="profil">
        <div class="avatar">
            <img class="thumbnail" src="<?php echo RESOURCES_BASEURL . '/images/avatar_sportif2.jpg'; ?>"/>
        </div>
        <address>
            <strong>Résponsable Evénementiel sportif</strong><br>Eddy Pillot<br>
            <a href="mailto:#">evenementiel.sportif@bdemiagenancy.fr</a>
        </address>
    </div>



    <div id="partner">
        <h3>Partenaires</h3>
        <hr>

        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object" src="<?php echo RESOURCES_BASEURL . '/images/logo-cgi.png'; ?>">
            </a>
                <div class="media-body">
                  <h4 class="media-heading">Groupe CGI</h4>
                  <blockquote>
                    <small>Technologies de l’information et gestion des processus d’affaires | services en TI de CGI</small>
                  </blockquote>

                <div class="media">
                    CGI propose toutes les solutions d'affaires en technologie de l'information (TI) incluant la gestion de fonctions informatiques et d'affaires (impartition), l'intégration de systèmes et le service-conseil.
                </div>
            </div>
        </div>


        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object" src="<?php echo RESOURCES_BASEURL . '/images/logoMIL.png'; ?>">
            </a>
                <div class="media-body">
                  <h4 class="media-heading">La MIL</h4>
                  <blockquote>
                    <small>La MIL, (Reseau des MIAGistes importés au Luxembourg)</small>
                  </blockquote>

                <div class="media">
                    <ul >
                        <li>Un réseau fédérant les miagistes diplômés ayant étudié dans n’importe quelle MIAGE (formation en France et pays étrangers) travaillant au Luxembourg;</li>
                        <li>Intégration des miagistes venant travailler au Luxembourg, en les accompagnant à travers les différentes démarches administratives et les subtilités propres au Luxembourg;</li>
                        <li>aider les membres à trouver un emploi au Luxembourg;</li>
                        <li>aider les membres à trouver un logement.</li>
                    </ul>
                    Plus d’infos sur : <a href="http://www.assomil.lu/">La MIL</a>.
                </div>
            </div>
        </div>


        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object" src="<?php echo RESOURCES_BASEURL . '/images/mgel.jpg'; ?>">
            </a>
                <div class="media-body">
                  <h4 class="media-heading">MGEL</h4>
                  <blockquote>
                    <small>La Sécurité sociale de près de 8 étudiants sur 10 dans l'Est de la France.</small>
                  </blockquote>

                <div class="media">
                    La MGEL est partenaire du BDE. Avec son « Pack MGEL », 
                    elle propose pour 25€ par an une assurance responsabilité 
                    civile (obligatoire pour tous les étudiants) et de 
                    nombreux avantages et réductions. Plus d’infos sur : <a href="http://www.mgel.fr">http://www.mgel.fr</a>.
                </div>
            </div>
        </div>

        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object" src="<?php echo RESOURCES_BASEURL . '/images/miageco.png'; ?>">
            </a>
                <div class="media-body">
                  <h4 class="media-heading">MIAGE Connection</h4>
                  <blockquote>
                    <small>MIAGE Connection, la fédération nationale des étudiants et diplômés de MIAGE.</small>
                  </blockquote>

                <div class="media">
                    <ul >
                        <li>Participer à la promotion du diplôme MIAGE</li>
                        <li>Représenter les étudiants et défendre leurs intérêts  au niveau national</li>
                        <li>Créer un réseau solide et durable entre étudiants et autres acteurs de la MIAGE</li>
                        <li>Aider et participer au développement des associations membres</li>
                    </ul>
                    Plus d’infos sur : <a href="http://www.miage.net/miageconnection/presentation">MIAGE Connection</a>.
                </div>
            </div>
        </div>

        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object" src="<?php echo RESOURCES_BASEURL . '/images/feden.jpg'; ?>">
            </a>
                <div class="media-body">
                  <h4 class="media-heading">FéDEN</h4>
                  <blockquote>
                    <small>La Fédération des Etudiants Nancéiens.</small>
                  </blockquote>

                <div class="media">
                    Depuis sa création en 1997, elle cherche à :
                    <ul >
                        <li>Fédérer et développer les assos étudiantes, corpos et BDE de NANCY</li>
                        <li>Défendre les intérêts moraux et matériels des étudiants de Nancy et son agglomération</li>
                        <li>Représenter les associations membres auprès des autorités territoriales et universitaires</li>
                        <li>Resserrer les liens d’amitié entre les associations</li>
                        <li>Exprimer la position des associations qu’elle représente</li>
                    </ul>
                    Plus d’infos sur : <a href="http://www.feden.org">http://www.feden.org</a>.
                </div>
            </div>
        </div>


    </div>

</section>

    



