<?php
    $this->headTitle('Statuts');
?>
   
<section>
    
    <h3><span style="text-decoration: underline;"><strong>I &ndash; But et composition de l&rsquo;Association:</strong></span></h3>
    <p><strong>Article 1er :</strong></p>
    <p>L&rsquo;association dite &laquo; Bureau des El&egrave;ves de la Miage Nancy &raquo; fond&eacute;e en 1974 a pour<br />but :</p>
    <p>1- D&rsquo;&eacute;tablir entre tous ses membres de relations amicales et des liens de solidarit&eacute; et<br />d&rsquo;entraide.<br />2- D&rsquo;utiliser ces relations dans un but d&rsquo;int&eacute;r&ecirc;t g&eacute;n&eacute;ral et au profit des associations<br />3- De contribuer &ccedil; la prosp&eacute;rit&eacute; et au rayonnement de la MIAGE , notamment en mettant<br />en &oelig;uvre tous les moyens propres &agrave; assurer l&rsquo;efficacit&eacute; de l&rsquo;enseignement pratiqu&eacute; &agrave; la<br />MIAGE.</p>
    <p>Sa dur&eacute;e est illimit&eacute;e.</p>
    <p>Elle a son si&egrave;ge social &agrave; :</p>
    <p>UFR Math&eacute;matiques et Informatique<br />13, rue Michel Ney<br />54000 Nancy</p>
    <p><strong>Article 2 :</strong></p>
    <p>Les moyens d&rsquo;action de l&rsquo;association sont : Bourses, secours, conf&eacute;rence,<br />publications, soir&eacute;es.</p>
    <p><strong>Article 3 :</strong></p>
    <p>L&rsquo;association se compose de membres titulaires et honoraires :<br />- Les membres titulaires doivent &ecirc;tre inscrit a la MIAGE de Nancy<br />- Les membres honoraires sont nomm&eacute;s par le Conseil d&rsquo;Administration.</p>
    <p>Ce membres sont choisis parmi les personnalit&eacute;s qui ont rendu ou peuvent rendre des<br />services &agrave; l&rsquo;Association. Ils ne sont tenus &agrave; aucune cotisation.</p>
    <p>-</p>
    <p>Les membres titulaires versent une cotisation pour leur inscription de 15&euro;.</p>
    <p><strong>Article 4 :</strong></p>
    <p>La qualit&eacute; de membre se perd par :</p>
    <p>1- D&eacute;mission<br />2- Radiation prononc&eacute;e pour le non-paiement de la cotation ou pour<br />motif graves par le Conseil d&rsquo;Administration, le membre int&eacute;ress&eacute;<br />ayant &eacute;t&eacute; pr&eacute;alablement appel&eacute; &agrave; fournir des explications.</p>
    <h3><span style="text-decoration: underline;"><strong>II : Administration et fonctionnement :</strong></span></h3>
    <p><strong>Article 5 :</strong></p>
    <p>L&rsquo;association est administr&eacute;e par un conseil compos&eacute; de 7 membres<br />(Pr&eacute;sident, Vice-pr&eacute;sident, tr&eacute;sorier, secr&eacute;taire, charg&eacute; de communication, charg&eacute;<br />&eacute;v&eacute;nementiel, webmaster), &eacute;lus pour un an par l&rsquo;assembl&eacute;e g&eacute;n&eacute;rale et choisis parmi les<br />membres dont se compose cette assembl&eacute;e.</p>
    <p>Le renouvellement du conseil a lieu en totalit&eacute;.</p>
    <p>Les membres sortants sont r&eacute;&eacute;ligibles.</p>
    <p>Le bureau est compos&eacute; du Pr&eacute;sident, Vice-pr&eacute;sident, tr&eacute;sorier, secr&eacute;taire,<br />charg&eacute; de communication, charg&eacute; &eacute;v&eacute;nementiel, webmaster.</p>
    <p><strong>Article 6 :</strong></p>
    <p>Le conseil se r&eacute;unit trimestriellement et chaque fois qu&rsquo;il est convoqu&eacute; par son<br />pr&eacute;sident ou sur la demande du tiers de ses membres.</p>
    <p>La pr&eacute;sence du tiers des membres du conseil d&rsquo;Administration est n&eacute;cessaire pour<br />la validit&eacute; des d&eacute;lib&eacute;rations.</p>
    <p>Il est tenu proc&egrave;s verbal des s&eacute;ances.</p>
    <p>Les proc&egrave;s-verbaux sont sign&eacute;s par le Pr&eacute;sident et le Secr&eacute;taire, ils sont transmis<br />sans blanc ni nature sur un registre cot&eacute; et paraph&eacute; par le Pr&eacute;fet ou son d&eacute;l&eacute;gu&eacute;.</p>
    <p><strong>Article 7 :</strong></p>
    <p>Les membres de l&rsquo;Association ne peuvent recevoir aucune r&eacute;tribution en raison des<br />fonctions qui leur sont confi&eacute;es. Seule la gratuit&eacute; des soir&eacute;es organis&eacute;es pour les membres<br />du bureau sera accept&eacute;e.</p>
    <p><strong>Article 8 :</strong></p>
    <p>L&rsquo;assembl&eacute;e G&eacute;n&eacute;rale de l&rsquo;Association comprend tous les membres.</p>
    <p>Elle se r&eacute;unit une fois par an et chaque fois qu&rsquo;elle est convoqu&eacute;e par le Conseil<br />d&rsquo;Administration ou sur la demande du quart a moins de ses membres.</p>
    <p>Son ordre du jour est r&eacute;gl&eacute; par le Conseil d&rsquo;Administration.</p>
    <p>Son bureau est celui du conseil.</p>
    <p>Elle entend les rapports sur la gestion du Conseil d&rsquo;Administration, sur la situation<br />financi&egrave;re et morale de l&rsquo;association.</p>
    <p>Elle approuve les comptes de l&rsquo;exercice clos, vote le budget de l&rsquo;exercice suivant ,<br />d&eacute;lib&egrave;re sur les questions mises &agrave; l&rsquo;ordre du jour et pourvoit au renouvellement des<br />membres du Conseil d&rsquo;Administration.</p>
    <p><strong>Article 9 :</strong></p>
    <p>Les d&eacute;penses sont ordonnanc&eacute;es par le Pr&eacute;sident. L&rsquo;association est repr&eacute;sent&eacute;e en<br />justice et dans tous les actes de la vie civile par le pr&eacute;sident ou son repr&eacute;sentant.<br />Le repr&eacute;sentant de l&rsquo;association doit jouir du plein exercice de ses droits civils.</p>
    <p><strong>Article 10 :</strong></p>
    <p>Il est tenu au jour le jour une comptabilit&eacute;-deniers par recettes et par d&eacute;penses,<br />et, s&rsquo;il y a lieu, une comptabilit&eacute; mati&egrave;res.</p>
    <h3><span style="text-decoration: underline;"><strong>III : Changement, modifications, et dissolution.</strong></span></h3>
    <p><strong>Article 11 :</strong></p>
    <p>Le pr&eacute;sident doit faire connaitre dans les 3 mois, &agrave; la Pr&eacute;fecture de la Meurthe-<br />et-Moselle, tout le changement survenu dans l&rsquo;administration ou la direction de<br />l&rsquo;association ainsi que toutes les modifications apport&eacute;es &agrave; leurs statuts.</p>
    <p>Ces modifications et changement sont en outre consign&eacute;s sur le registre sp&eacute;cial<br />cot&eacute; et paraph&eacute;.</p>
    <p>Les registres de l&rsquo;association et ses pi&egrave;ces de comptabilit&eacute; sont pr&eacute;sent&eacute;s sans<br />d&eacute;placement, sur tout r&eacute;quisition du Pr&eacute;fet, &agrave; lui-m&ecirc;me ou a son d&eacute;l&eacute;gu&eacute; ou a tout<br />fonctionnaire accr&eacute;dit&eacute; par lui.</p>
    <p><strong>Article 12 :</strong></p>
    <p>La dissolution de l&rsquo;association ne peut &ecirc;tre prononc&eacute;e que par l&rsquo;assembl&eacute;e<br />g&eacute;n&eacute;rale convoqu&eacute;e sp&eacute;cialement &agrave; cet effet.</p>
    <p>L&rsquo;assembl&eacute;e g&eacute;n&eacute;rale d&eacute;signe un ou plusieurs commissaires charg&eacute;s de la<br />liquidation des biens de l&rsquo;Association.<br />Elle attribue l&rsquo;actif net conform&eacute;ment &agrave; la loi.</p>
    <p>La dissolution doit faire l&rsquo;objet d&rsquo;une d&eacute;claration &agrave; la Pr&eacute;fecture ou a la Sous-<br />pr&eacute;fecture du si&egrave;ge social.</p>

</section>
                        