<?php
$this->headTitle('Mots-clefs');
?>


<div class="row-fluid">
    <div class="box span12">
        
        <div class="box-header">
            <h2><i class="icon-edit"></i><span class="break"></span>Ajouter un tag</h2>
            <div class="box-icon">
                <a href="#" class="btn-minimize"><i class="icon-chevron-up"></i></a>
            </div>
        </div>
        
        <div class="box-content">
            
            <!-- add form -->
            <form enctype="application/x-www-form-urlencoded" 
                  method="<?php echo $this->form->getMethod() ?>" 
                  action="<?php echo $this->form->getAction()?>" 
                  class="form-horizontal">
                
                <fieldset>
                
                <div class="control-group">
                    <label class="control-label" for="">Nom</label>
                    <div class="controls">
                        <input class="input-xxlarge" id="label" name="label" type="text" value="<?php echo $this->form->getValue('label'); ?>" data-rel="tooltip" data-placement="bottom" data-original-title="">
                        <span class="help-inline red">Requis</span>
                    </div>
                </div>
                    
                <div class="control-group">
                    <label class="control-label" for="">Description</label>
                    <div class="controls">
                        <textarea name="description" id="description" class="input-xxlarge" rows="5" cols="80"><?php echo $this->form->getValue('description'); ?></textarea>
                    </div>
                </div>

                <div class="form-actions">
                    <button type="submit" name="submit" id="submit" class="btn btn-primary btn-submit">Ajouter le mot-clef</button>
                    <button class="btn" type="reset">Annuler</button>
                </div>
                
                </fieldset>
            </form>
            <!-- end: add form -->
            
        </div>
    </div><!--/span-->
</div>



<div class="row-fluid">		
    <div class="box span12">
        
        <div class="box-header" data-original-title="">
                <h2><i class="icon-user"></i><span class="break"></span>Catégories enregistrées</h2>
        </div>
        
        <div class="box-content">
            
            <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
                <thead>
                    <tr>
                        <th style="width: 50px;">Identifiant</th>
                        <th>Label</th>
                        <th>Description</th>
                        <th style="width: 95px;">Action</th>
                    </tr>
                </thead>   

                <tbody >

                    <?php foreach($this->tags as $tag): ?>
                    <tr>
                        <td><?php echo $tag->id; ?></td>
                        <td class="center "><?php echo $tag->label; ?></td>
                        <td class="center "><?php echo $tag->description; ?></td>
                        <td class="center ">
                            
                            <!-- update -->
                            <?php if( $this->isAllowed('admin_tag', 'update')): ?>
                                <a class="btn btn-info" href="<?php echo $this->url(array('controller'=> 'tag', 'action' => 'update', 'module' => 'admin', 'id' => $tag->id),'default',true); ?>">
                                    <i class="icon-edit icon-white"></i>
                                </a>
                            <?php endif; ?>
                            
                            <!-- remove -->
                            <?php if( $this->isAllowed('admin_tag', 'remove')): ?>
                            <a class="btn btn-danger confirm-action" href="<?php echo $this->url(array('controller'=> 'tag', 'action' => 'remove', 'module' => 'admin', 'id' => $tag->id),'default',true); ?>" data-message="Êtes-vous sûr de vouloir supprimer ce tag ?">
                                <i class="icon-trash icon-white"></i> 
                            </a>
                            <?php endif; ?>
                            
                        </td>
                    </tr>
                    <?php endforeach; ?>

                </tbody>
            </table>
        </div>            
    </div>
</div><!--/span-->