<?php
$this->headTitle('Catégories - Modification');
?>

<div class="row-fluid">
    <div class="box span12">
        
        <div class="box-header">
            <h2><i class="icon-edit"></i><span class="break"></span>Modification de la catégorie <?php echo $this->escape($this->category->label); ?></h2>
        </div>
        
        <div class="box-content">
            
            <!-- add form -->
            <form enctype="application/x-www-form-urlencoded" 
                  method="post" 
                  action="<?php echo $this->form->getAction()?>" 
                  class="form-horizontal">
                
                <fieldset>
                
                    <div class="control-group">
                        <label class="control-label" for="">Nom</label>
                        <div class="controls">
                            <input class="input-xxlarge" id="title" name="title" type="text" value="<?php echo $this->form->getValue('title'); ?>" data-rel="tooltip" data-placement="bottom" data-original-title="">
                            <span class="help-inline red">Requis</span>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="">Label</label>
                        <div class="controls">
                            <input class="input-xxlarge" id="label" name="label" type="text" value="<?php echo $this->form->getValue('label'); ?>" data-rel="tooltip" data-placement="bottom" data-original-title="">
                            <span class="help-inline red">Requis</span>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="">Description</label>
                        <div class="controls">
                            <textarea name="description" id="description" class="input-xxlarge" rows="5" cols="80"><?php echo $this->form->getValue('description'); ?></textarea>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="">Catégorie parente</label>
                        <div class="controls">
                            <?php echo $this->form->getElement('parentId')->renderViewHelper(); ?>
                        </div>
                    </div>

                    <div class="form-actions">
                        <button type="submit" name="submit" id="submit" class="btn btn-primary btn-submit">Modifier</button>
                        <button class="btn" type="reset">Annuler</button>
                    </div>
                
                </fieldset>
            </form>
            <!-- end: add form -->
            
        </div>
    </div><!--/span-->
</div>